### ISSUE TITLE
Replace fonts with Google Fonts

### ISSUE THREAD

**Issue by rolandixor** [hyrmn/snippitbox#1]
I'm probably going to do this upstream, for convenience.

**Comment by hyrmn** [comment]
Thanks @rolandixor I'm really attached to Inter Var and use it everywhere, but I saw you had all of the fonts in the CSS and I know better than to mess with a designer's vision 😁

**Comment by rolandixor** [comment]
Well, the good news is, with the updates I've made upstream, that'll be pretty easy to swap in. You won't get support for IE11 though lol

**Comment by hyrmn** [comment]
Resolved with 50fdd269b2bbc39694bc619894a7d540a3eac5ef

I'm on the latest and greatest!
